### ISSUE TITLE
Unable to access to all series in .czi files

### ISSUE THREAD

**Issue by ShanJiangEmugen** [bioio-devs/bioio-czi#20]
Hi there,

I currently have some images taken from Zeiss AxioScan, which stored images in a slightly different .czi format than my previous scanning. The new .czi file will stack all slices/scenes together and name each of them as "series #" when I open it in ImageJ, please see the attached ImageJ screenshot. However, when I load those .czi files with Python, I cannot select the "series #". It only loads the first "series". Are there any features in this bioio that can handle this issue? I have tried AICSImageIO, but seems it has nothing to do with this issue. 

I used Google Colab for this project, so there shouldn't be any environment-related issues. 

Thanks a lot in advance! 

![截图 2024-10-31 14-57-25](https://github.com/user-attachments/assets/c89245a1-2e2a-403f-bea2-0eaa68177678)

**Comment by toloudis** [comment]
It sounds like what you want is the concept of `BioImage.scenes` and `BioImage.set_scene`:
https://bioio-devs.github.io/bioio/bioio.html#bioio.bio_image.BioImage.scenes

**Comment by ShanJiangEmugen** [comment]
Thanks for your help! 

I tried the` BioImage.scenes` method but it still didn't recognize the "Series". Please see the attached.

I guess that's one of the new features of Zessi equipment. My current workaround is to get each image through ImageJ Marco. 

![image](https://github.com/user-attachments/assets/48669157-59de-4359-9845-2da821e62172)

**Comment by BrianWhitneyAI** [comment]
hey @ShanJiangEmugen Thanks again for your submission. I'm sorry the `.scenes` functionality isn't working for you. Do you have some test files that you could provide so I can look into this issue further?

**Comment by sebi06** [comment]
What is shown in the imageJ screenshot of how bioformats interprets the pyramid level of a CZI as series.

This is perfectly normal for CZIs and has nothing to do with the new device as all our system just write CZI.

But one can use aicspylibczi or pylibczirw to read the desired zoomlevels from a CZI.

**Comment by pgarrison** [comment]
@bellonet, since you say your CZI has no pyramidal structure, I think you have a different issue. Can you open a new issue with the steps to reproduce your issue, the actual behavior, the expected behavior, and the link to your example image?

**Comment by ShanJiangEmugen** [comment]
> [@ShanJiangEmugen](https://github.com/ShanJiangEmugen) From the discussion above, it sounds like you are trying to access the multiple zoom/resolution levels of a pyramidal scene. This feature is not currently provided by bioio-czi, but it would be a welcome addition if anyone wants to implement it. I'm not sure aicspylibczi provides access to all the resolution levels of a CZI, but pylibczirw does, so this might be a feature for just pylibczirw mode. Here's what that would involve:
> 
> * Implement the `resolution_levels` [function](https://github.com/bioio-devs/bioio-base/blob/0cec271ceab67fcd78efd5f53b4169c9858a6b80/bioio_base/reader.py#L209) in the pylibczirw reader
> * Implement the `set_resolution_level` [function](https://github.com/bioio-devs/bioio-base/blob/0cec271ceab67fcd78efd5f53b4169c9858a6b80/bioio_base/reader.py#L316C9-L316C29) in the pylibczirw reader, being sure to set the `_total_bounding_box` and `_scenes_bounding_rectangle` properties based on the new resolution level.
> * Update [the line in the pylibczirw reader](https://github.com/bioio-devs/bioio-czi/blob/main/bioio_czi/pylibczirw_reader/reader.py#L246C26-L246C30) that reads the pixel data to use pylibczirw's [zoom parameter](https://github.com/ZEISS/pylibczirw/blob/main/API.md#zoom) based on the selected resolution level.

Thanks for the suggestion! I’ll explore the `pylibczirw` integration and see what I can do to support resolution levels.

**Comment by ShanJiangEmugen** [comment]
Hi @pgarrison, I was able to implement the zoom/resolution feature in the bioio-czi reader. However, I encountered a shape mismatch error even after updating both _total_bounding_box and _scenes_bounding_rectangle. To resolve this, I had to modify the _read_delayed() method. Is this an expected behavior when working with different resolution levels?

Also, I came across this issue in the pylibCZIrw repository: [ZEISS/pylibczirw#80](https://github.com/ZEISS/pylibczirw/issues/80). It looks related and might provide some useful context. @bellonet

**Comment by ShanJiangEmugen** [comment]
Hi @pgarrison, I was able to implement the zoom/resolution feature in the `bioio-czi` `reader`. However, I encountered a shape mismatch error even after updating both `_total_bounding_box` and `_scenes_bounding_rectangle`. To resolve this, I had to modify the `_read_delayed()` method. Is this an expected behavior when working with different resolution levels?

Also, I came across this issue in the `pylibCZIrw` repository: [ZEISS/pylibczirw#80](https://github.com/ZEISS/pylibczirw/issues/80). It looks related and might provide some useful context.
Tagging @bellonet for visibility.

**Comment by pgarrison** [comment]
> I was able to implement the zoom/resolution feature in the bioio-czi reader.

Wonderful! Thanks for working on this!

> However, I encountered a shape mismatch error even after updating both _total_bounding_box and _scenes_bounding_rectangle. To resolve this, I had to modify the _read_delayed() method. Is this an expected behavior when working with different resolution levels?

Hm, I'm not sure. If you push your changes to your fork I can take a look.

**Comment by sebi06** [comment]
The shape differences were the caused by discrepancies between size metadata and bounding boxes with or without pyramid?

Are there any details on this topic?

**Comment by ShanJiangEmugen** [comment]
I’ve pushed my changes to the pyramid_zoom branch on my fork. I tested the new features on several images, both with and without pyramid structures, and they appear to work as expected. However, I’m not completely sure whether my .czi files fully conform to the standard format.

When I didn’t modify the _read_delayed() function and instead hardcoded the new shapes in the set_resolution_level function, I encountered the following error, and the changes didn’t work.

Traceback (most recent call last):
  File "/home/emugentx/Desktop/bioio-czi/test_set_resolution_level.py", line 11, in <module>
    img = reader.xarray_data  # Trigger actual read
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/bioio_base/reader.py", line 453, in xarray_data
    self._xarray_data = self._read_immediate()
  File "/home/emugentx/Desktop/bioio-czi/bioio_czi/pylibczirw_reader/reader.py", line 349, in _read_immediate
    return self._read_delayed().compute()
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/xarray/core/dataarray.py", line 1189, in compute
    return new.load(**kwargs)
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/xarray/core/dataarray.py", line 1157, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/xarray/core/dataset.py", line 547, in load
    self.variables[k].data = data
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/xarray/core/variable.py", line 445, in data
    self._check_shape(data)
  File "/media/emugentx/Disk1/miniconda3/envs/bioio-czi-dev/lib/python3.10/site-packages/xarray/namedarray/core.py", line 537, in _check_shape
    raise ValueError(
ValueError: replacement data must match the Variable's shape. replacement data has shape (3, 1393, 2662); Variable has shape (3, 5574, 10651)
